//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTwain.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NTwain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data group for application must contain either Image or Audio..
        /// </summary>
        internal static string BadDataGroupsForAppId {
            get {
                return ResourceManager.GetString("BadDataGroupsForAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid value type for {0}..
        /// </summary>
        internal static string BadValueType {
            get {
                return ResourceManager.GetString("BadValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capability {0} has invalid container type {1}..
        /// </summary>
        internal static string CapHasBadContainer {
            get {
                return ResourceManager.GetString("CapHasBadContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The string value has exceeded the maximum length allowed..
        /// </summary>
        internal static string MaxStringLengthExceeded {
            get {
                return ResourceManager.GetString("MaxStringLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message loop has not started yet..
        /// </summary>
        internal static string MsgLoopUnavailble {
            get {
                return ResourceManager.GetString("MsgLoopUnavailble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source name is required..
        /// </summary>
        internal static string SourceRequired {
            get {
                return ResourceManager.GetString("SourceRequired", resourceCulture);
            }
        }
    }
}
